### ISSUE TITLE
Cannot read property 'errored' of undefined

### ISSUE THREAD

**Issue by amk221** [billybonks/broccoli-stylelint#18] opened 2016-10-10 08:44 UTC
This morning our builds started failing, with this error:

```
The Broccoli Plugin: [StyleLinter] failed with:
TypeError: Cannot read property 'errored' of undefined
    at StyleLinter.postProcess (/Users/andrew/src/foo/ember/node_modules/broccoli-stylelint/index.js:137:12)
    at /Users/andrew/src/foo/ember/node_modules/broccoli-persistent-filter/lib/strategies/default.js:21:21
    at initializePromise (/Users/andrew/src/foo/ember/node_modules/rsvp/dist/rsvp.js:588:5)
    at new Promise (/Users/andrew/src/foo/ember/node_modules/rsvp/dist/rsvp.js:1076:31)
    at /Users/andrew/src/foo/ember/node_modules/broccoli-persistent-filter/lib/strategies/default.js:20:14
    at tryCatch (/Users/andrew/src/foo/ember/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/andrew/src/foo/ember/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/andrew/src/foo/ember/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/Users/andrew/src/foo/ember/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by pfmmfp** [comment] 2016-10-11 16:38
Same here using the following versions,

```
ember-cli-stylelint@0.6.2 node_modules/ember-cli-stylelint
├── broccoli-funnel@1.0.7 (fast-ordered-set@1.0.3, blank-object@1.0.2, symlink-or-copy@1.1.6, array-equal@1.0.0, path-posix@1.0.0, walk-sync@0.3.1, fs-tree-diff@0.5.3, debug@2.2.0, minimatch@3.0.3, mkdirp@0.5.1, rimraf@2.5.4, broccoli-plugin@1.2.2, heimdalljs@0.2.1)
└── broccoli-stylelint@0.8.3 (js-string-escape@1.0.1, merge@1.2.0, broccoli-persistent-filter@1.2.11, stylelint@7.4.2)
```

**Comment by pfmmfp** [comment] 2016-10-24 20:36
So I've found that the error started to show up with stylelint 7.4.0. It can be reproduced by cloning latest master and running tests with `npm test`.

It seems that starting from that version, stylelint requires that the `codeFilename` parameter can actually be resolved in the filesystem. Not completely sure, but [this one](https://github.com/stylelint/stylelint/pull/1930) might have caused it.

The PR I've just sent has the intention of fixing this problem by prepending the `inputNodes` directory in the `relativePath` that corresponds to each of the files being linted -- [ref this line](https://github.com/billybonks/broccoli-stylelint/pull/22/files#diff-168726dbe96b3ce427e7fedce31bb0bcR134)

Not sure if this is the best approach in regards to broccoli best practices, but got some inspiration based on the [eslint plugin](https://github.com/ember-cli/broccoli-lint-eslint/blob/2.x/lib/index.js#L64), although improved it to use the [broccoli-node-info](https://github.com/broccolijs/broccoli-node-info) wrapper.

@billybonks what do you think?

**Comment by billybonks** [comment] 2016-11-02 16:06
Hey guys, i really need to setup a watcher for issues created on the repo 👍 just wanted to let you know that i am going to look through all of this and get back to you very soon @pfmmfp thanks for the prerequisite research

**Comment by williamweckl** [comment] 2016-11-09 11:20
HI guys, any news on this one? Is there a way to do a temporary fix?

**Comment by billybonks** [comment] 2016-11-09 14:06
so i have released `ember-cli-stylelint` v0.6.3 it has locked the versions of every dependency so that this doesn't happen again. 

for now we will be on stylelint version 7.3 i will work with @pfmmfp to solve this asap so we can get new versions :)

**Closed** 2016-11-09 15:18 UTC

**Comment by billybonks** [comment] 2016-11-09 15:21
@amk221 so i merged @pfmmfp's pull request but would like to make sure it works with your setup. since it is the most interesting one https://github.com/billybonks/ember-cli-stylelint/issues/3. can you test this for us


change the dependency in ember `ember-cli-stylelint` of `broccoli-stylelint` to   

"broccoli-stylelint": "billybonks/broccoli-stylelint#master",

**Comment by amk221** [comment] 2016-11-10 11:13
@billybonks Thanks, I tried that and it worked.

**Comment by williamweckl** [comment] 2016-12-06 17:46
Worked for me too. Thanks!

**Comment by rwwagner90** [comment] 2019-06-18 18:34
I'm seeing this again now, on latest ember-cli-stylelint. Does anyone know of a fix?

**Comment by amk221** [comment] 2019-06-18 20:05
I moved away from ember-cli-stylelint and therefore also broccoli-stylint, in favour of adding this to package.json in our app

```
“scripts”: {
  "lint:css": "stylelint '**/*.{css,scss}'”
}
```

**Comment by rwwagner90** [comment] 2019-06-19 14:40
@amk221 that removes the unit tests for failing stylelint though, which I think is nice to have.

**Comment by amk221** [comment] 2019-06-19 14:41
@rwwagner90 Sorry I should have clarified `"test": "yarn exam && yarn lint"`

**Comment by rwwagner90** [comment] 2019-06-19 14:43
@amk221 you still lose the ability to generate unit tests for failing stylelint is what I mean. I like how ember-cli-stylelint and ember-cli-eslint generate unit tests for you.

**Comment by billybonks** [comment] 2019-06-19 16:22
will aim to have this resolved by this time tomorrow, still working on my end :/
